# Generated by Django 3.1.7 on 2023-04-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
