# Generated by Django 3.1.7 on 2023-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name': 'Instituto', 'verbose_name_plural': 'Institutos'},
        ),
        migrations.AlterField(
            model_name='institute',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
