# Generated by Django 3.1.7 on 2023-04-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_classroom_examcenter'),
        ('announcement', '0001_initial'),
        ('institute', '0002_auto_20230415_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenterAssignment',
            fields=[
                ('assign_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id asignacion')),
                ('seats', models.PositiveSmallIntegerField(default=0, verbose_name='Nº Plazas')),
                ('announcement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement', verbose_name='Id sala')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.classroom', verbose_name='Id sala')),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute', verbose_name='Id sala')),
            ],
            options={
                'verbose_name': 'Asignación centro de examen',
                'verbose_name_plural': 'Asignaciones centros de examen',
            },
        ),
    ]
