# Generated by Django 3.1.7 on 2023-04-16 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_examcenterassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcenterassignment',
            name='institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_centers', to='institute.institute', verbose_name='Id sala'),
        ),
    ]
