# Generated by Django 3.1.7 on 2023-04-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
        ('institute', '0004_auto_20230416_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcenterassignment',
            name='announcement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement', verbose_name='Id convocatoria'),
        ),
        migrations.AlterField(
            model_name='examcenterassignment',
            name='institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_centers', to='institute.institute', verbose_name='Id instituto'),
        ),
    ]
