# Generated by Django 3.1.7 on 2023-04-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
