# Generated by Django 3.1.7 on 2023-04-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phase', '0002_auto_20230415_1253'),
        ('modality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nombre')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.category', verbose_name='Id categoria')),
                ('modality_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modality.modality', verbose_name='Id modalidad')),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phase.phase', verbose_name='Id fase')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
    ]
