# Generated by Django 3.1.7 on 2023-04-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modality', '0001_initial'),
        ('subject', '0003_auto_20230416_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='modality_id',
        ),
        migrations.CreateModel(
            name='SubjectModality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.modality', verbose_name='Modality')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Modalidad Asigntura',
                'verbose_name_plural': 'Modalidades Asignatura',
                'unique_together': {('subject_id', 'modality_id')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='modality_id',
            field=models.ManyToManyField(related_name='subjects', through='subject.SubjectModality', to='modality.Modality'),
        ),
    ]
