# Generated by Django 3.1.7 on 2023-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20230429_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre'),
        ),
    ]
