# Generated by Django 3.1.7 on 2023-06-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20230429_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('obligatoria', 'Obligatoria'), ('opcion', 'Opcion')], default='opcion', max_length=15),
        ),
    ]
