# Generated by Django 3.1.7 on 2023-04-29 15:59

import apps.institute_staff.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20230429_1759'),
        ('institute', '0005_auto_20230417_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteStaff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.useraccount')),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.institute_staff.models.staff_photo_directory)),
                ('doc_type', models.CharField(choices=[('dip', 'DIP'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='dip', max_length=20)),
                ('doc_number', models.CharField(max_length=10)),
                ('job_title', models.CharField(choices=[('secretario', 'Secretario'), ('director', 'director')], default='secretario', max_length=30)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institute.institute')),
            ],
            options={
                'verbose_name': 'Personal Instituto',
                'verbose_name_plural': 'Personal Institutos',
            },
        ),
    ]
