# Generated by Django 3.1.7 on 2023-04-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('list_submision_start', models.DateTimeField()),
                ('list_submision_end', models.DateTimeField()),
                ('enrollment_start', models.DateTimeField()),
                ('enrollment_end', models.DateTimeField()),
                ('grades_publication', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
            },
        ),
    ]
