# Generated by Django 3.1.7 on 2023-04-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0004_auto_20230429_1939'),
        ('exam', '0003_auto_20230417_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(max_length=4, verbose_name='Nota')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollment.enrollment', verbose_name='Matricula')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exam.exam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
