# Generated by Django 3.1.7 on 2023-05-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_auto_20230430_1641'),
        ('exam', '0003_auto_20230417_0930'),
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'exam_id')},
        ),
    ]
