# Generated by Django 3.1.7 on 2023-06-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20230417_0930'),
        ('enrollment', '0009_auto_20230603_0448'),
        ('grade', '0002_auto_20230511_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment', verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam'),
        ),
    ]
