# Generated by Django 3.1.7 on 2023-04-29 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modality', '0002_auto_20230429_2019'),
        ('degree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalityDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree.degree', verbose_name='Carrera')),
                ('modality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.modality', verbose_name='Modalidad')),
            ],
            options={
                'verbose_name': 'Modalidad Carrera',
                'verbose_name_plural': 'Modalidades Carrera',
                'unique_together': {('degree_id', 'modality_id')},
            },
        ),
        migrations.AddField(
            model_name='degree',
            name='modality',
            field=models.ManyToManyField(through='degree.ModalityDegrees', to='modality.Modality', verbose_name='Modalidades'),
        ),
    ]
