# Generated by Django 3.1.7 on 2023-04-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0003_auto_20230416_0331'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False, verbose_name='codigo')),
                ('exam_date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('announcement_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='announcement.announcement', verbose_name='Id convocatoria')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subject.subject', verbose_name='id asignatura')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'unique_together': {('subject_id', 'announcement_id')},
            },
        ),
    ]
