# Generated by Django 3.1.7 on 2023-04-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_classroom_examcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examcenter', verbose_name='Centro'),
        ),
    ]
