# Generated by Django 3.1.7 on 2023-04-29 16:44

import apps.enrollment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
        ('student', '0002_auto_20230429_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('enroment_data', models.DateTimeField(verbose_name='Fecha Matricula')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio')),
                ('copy_id_card', models.FileField(max_length=500, upload_to=apps.enrollment.models.enrollment_docs_directory)),
                ('proof_of_payment', models.FileField(max_length=500, upload_to=apps.enrollment.models.enrollment_docs_directory)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='announcement.announcement', verbose_name='Convocatoria')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
    ]
