# Generated by Django 3.1.7 on 2023-04-29 16:49

import apps.enrollment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='copy_id_card',
            field=models.FileField(max_length=500, upload_to=apps.enrollment.models.enrollment_docs_directory, verbose_name='Copia documento identidad'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='proof_of_payment',
            field=models.FileField(max_length=500, upload_to=apps.enrollment.models.enrollment_docs_directory, verbose_name='Justificante pago'),
        ),
    ]
