# Generated by Django 3.1.7 on 2023-04-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
        ('student', '0002_auto_20230429_1759'),
        ('subject', '0003_auto_20230416_0331'),
        ('degree', '0001_initial'),
        ('enrollment', '0002_auto_20230429_1849'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'announcement')},
        ),
        migrations.CreateModel(
            name='EnrollmentSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment', verbose_name='Matricula')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura Matricula',
                'verbose_name_plural': 'Asignaturas Matricula',
                'unique_together': {('enrollment', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ChosenDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree.degree', verbose_name='Carrera')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment', verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Carrera elegida',
                'verbose_name_plural': 'Carreras elegidas',
                'unique_together': {('enrollment', 'degree')},
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='degrees',
            field=models.ManyToManyField(through='enrollment.ChosenDegrees', to='degree.Degree'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subjects',
            field=models.ManyToManyField(through='enrollment.EnrollmentSubjects', to='subject.Subject'),
        ),
    ]
