# Generated by Django 3.1.7 on 2023-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_auto_20230429_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
    ]
