# Generated by Django 3.1.7 on 2023-05-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20230417_0930'),
        ('enrollment', '0005_auto_20230430_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='exam_class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.classroom', verbose_name='Id sala'),
        ),
    ]
