# Generated by Django 3.1.7 on 2023-05-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20230417_0930'),
        ('enrollment', '0006_enrollment_exam_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'No Formalizada'), (1, 'Formalizada'), (2, 'Validada')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.classroom', verbose_name='Sala examen'),
        ),
    ]
