# Generated by Django 3.1.7 on 2023-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_auto_20230517_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status_id_card',
            field=models.SmallIntegerField(choices=[(0, 'Sin validar'), (1, 'Valido'), (2, 'No valido')], default=0, verbose_name='DNI Valido'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status_proof_payment',
            field=models.SmallIntegerField(choices=[(0, 'Sin validar'), (1, 'Valido'), (2, 'No valido')], default=0, verbose_name='Justificante Pago Valido'),
        ),
    ]
