# Generated by Django 3.1.7 on 2023-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_auto_20230519_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'No Formalizada'), (1, 'Formalizada'), (2, 'Validada'), (3, 'Valida Parcialmente')], default=0, verbose_name='Estado'),
        ),
    ]
