# Generated by Django 3.1.7 on 2023-04-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
    ]
