# Generated by Django 3.1.7 on 2023-05-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='doc_type',
            field=models.CharField(choices=[('dip', 'DIP'), ('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='dip', max_length=20),
        ),
    ]
